/**
 * tests/add_product_to_cart.test.js
 * Flow: add_product_to_cart
 * Auto-generated by Claude QA Pipeline
 */
const { expect }      = require('chai');
const { buildDriver } = require('../utils/driver');
const reporter        = require('../utils/reporter');
const LoginPage       = require('../pages/LoginPage');
const InventoryPage   = require('../pages/InventoryPage');
const config          = require('../config/test.config');

describe('Add Product to Cart Flow', function () {
  this.timeout(60000);
  let driver, loginPage, inventoryPage;

  before(async () => {
    reporter.startSuite();
    driver        = await buildDriver({ headless: config.headless });
    loginPage     = new LoginPage(driver);
    inventoryPage = new InventoryPage(driver);

    // Pre-condition: login
    await loginPage.open();
    await loginPage.login(config.credentials.validUser, config.credentials.password);
    await inventoryPage.waitForLoad();
  });

  after(async () => {
    if (driver) await driver.quit();
    reporter.writeResults('./results');
  });

  // ─── TC-006 · ZEPHYR: ZS-006 ────────────────────────────────────────────────
  it('[TC-006] Cart badge updates after adding first product', async function () {
    const start = Date.now();
    try {
      await inventoryPage.clickAddToCart(0);
      const count = await inventoryPage.getCartBadgeCount();
      expect(count).to.equal(1);

      reporter.record({
        tcId: 'TC-006', testCaseKey: process.env.TC_KEY_006 || 'ZS-006',
        name: 'Cart badge updates after adding first product',
        status: 'PASS', duration: Date.now() - start, error: null,
      });
    } catch (err) {
      reporter.record({
        tcId: 'TC-006', testCaseKey: process.env.TC_KEY_006 || 'ZS-006',
        name: 'Cart badge updates after adding first product',
        status: 'FAIL', duration: Date.now() - start, error: err.message,
      });
      throw err;
    }
  });

  // ─── TC-007 · ZEPHYR: ZS-007 ────────────────────────────────────────────────
  it('[TC-007] Cart badge increments when adding multiple products', async function () {
    const start = Date.now();
    try {
      await inventoryPage.clickAddToCart(1);
      const count = await inventoryPage.getCartBadgeCount();
      expect(count).to.equal(2);

      reporter.record({
        tcId: 'TC-007', testCaseKey: process.env.TC_KEY_007 || 'ZS-007',
        name: 'Cart badge increments when adding multiple products',
        status: 'PASS', duration: Date.now() - start, error: null,
      });
    } catch (err) {
      reporter.record({
        tcId: 'TC-007', testCaseKey: process.env.TC_KEY_007 || 'ZS-007',
        name: 'Cart badge increments when adding multiple products',
        status: 'FAIL', duration: Date.now() - start, error: err.message,
      });
      throw err;
    }
  });

  // ─── TC-008 · ZEPHYR: ZS-008 ────────────────────────────────────────────────
  it('[TC-008] Shopping cart icon navigates to cart page', async function () {
    const start = Date.now();
    try {
      await inventoryPage.clickCart();
      const url = await driver.getCurrentUrl();
      expect(url).to.include('cart.html');

      reporter.record({
        tcId: 'TC-008', testCaseKey: process.env.TC_KEY_008 || 'ZS-008',
        name: 'Shopping cart icon navigates to cart page',
        status: 'PASS', duration: Date.now() - start, error: null,
      });
    } catch (err) {
      reporter.record({
        tcId: 'TC-008', testCaseKey: process.env.TC_KEY_008 || 'ZS-008',
        name: 'Shopping cart icon navigates to cart page',
        status: 'FAIL', duration: Date.now() - start, error: err.message,
      });
      throw err;
    }
  });
});
